FROM docker.io/library/debian:bookworm-slim
# Use a minimal Debian base image for the mail server
LABEL maintainer="{{ email }}"

# Install postfix and dovecot dependencies

RUN apt-get update && \
    apt-get install -y procps \
    net-tools \
    postfix \
    dovecot-core \
    dovecot-imapd \
    supervisor \
    rsyslog \
    python3 \
    python3-pip \
    python3-venv \
    ipython3 \
    telnet \
    mailutils \
    mutt \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create a venvironment for the mail server management script
RUN python3 -m venv /usr/local/venv \
    && /usr/local/venv/bin/pip install --upgrade pip \
    && /usr/local/venv/bin/pip install --no-cache-dir requests flask

# Create app directory for the mail server management script
RUN mkdir -p /usr/local/actions

# Create virtual mail directory, user and group. This user will own the mail directories.
RUN useradd -r -u 5000 -g mail -d /var/vmail -s /sbin/nologin -c "Virtual Mail User" vmail \
    && mkdir -p /var/vmail \
    && chown vmail:mail /var/vmail \
    && chmod 770 /var/vmail

# Create the SSL/TLS certificate directory
RUN mkdir -p /etc/ssl/certs/server
RUN mkdir -p /etc/ssl/certs/letsencrypt


# Copy configuration files
COPY build/mail/main.cf /etc/postfix/main.cf
COPY build/mail/master.cf /etc/postfix/master.cf
COPY build/mail/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY build/mail/dovecot.conf /etc/dovecot/dovecot.conf


# Copy the mail server management scripts
COPY actions /usr/local/actions

# Make now_mail.py executable and create a symlink
RUN chmod +x /usr/local/actions/now_mail.py \
    && ln -s /usr/local/actions/now_mail.py /usr/local/bin/now_mail

# Create the admin and test users
RUN now_mail create_user --username admin --password adminpass123 --domain {{ domain }}
RUN now_mail create_user --username testuser --password testpass123 --domain {{ domain }}

# Expose SMTP port
EXPOSE 25 587
# Expose submission port
EXPOSE 465
# Expose IMAP port
EXPOSE 993
# Expose POP3 port
EXPOSE 995

# run supervisord to manage mail services
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
