FROM docker.io/library/httpd:2.4

# Install required packages
RUN apt-get update && apt-get install -y \
    cron \
    git \
    gitweb \
    nano \
    python3 \
    python3-certbot-apache \
    python3-passlib \
    python3-pip \
    python3-venv \
    && rm -rf /var/lib/apt/lists/*

# Create directories for certbot
RUN mkdir -p /etc/letsencrypt /var/lib/letsencrypt /var/log/letsencrypt

# Create directory for git repos
RUN mkdir -p /usr/local/apache2/git && chown -R www-data:www-data /usr/local/apache2/git

# Create directory for webdav
RUN mkdir -p /usr/local/apache2/webdav && chown -R www-data:www-data /usr/local/apache2/webdav

# Create directory for webdav.lock
RUN mkdir -p /usr/local/apache2/webdav.lock && chown -R www-data:www-data /usr/local/apache2/webdav.lock

# Create directory for actions
RUN mkdir -p /usr/local/actions

# Create an empty htpasswd file for git
RUN touch /usr/local/apache2/conf/git-auth && chown www-data:www-data /usr/local/apache2/conf/git-auth

# Copy the actions directory to the container
COPY actions /usr/local/actions

# Make now_mail.py executable and create a symlink
RUN chmod +x /usr/local/actions/now_mail.py \
    && ln -s /usr/local/actions/now_mail.py /usr/local/bin/now_mail \
    && ln -s /usr/local/actions/build.py /usr/local/bin/build

# Create directories for SSL certificates
RUN mkdir -p /usr/local/apache2/conf/ssl
