# Basic settings
listen = *
protocols = imap

# Logging
log_path = /dev/stdout
info_log_path = /dev/stdout
debug_log_path = /dev/stdout

# Authentication
disable_plaintext_auth = yes
auth_mechanisms = plain login

passdb {
    driver = passwd-file
    args = /etc/dovecot/passwd
}

userdb {
    driver = static
    args = uid=vmail gid=mail home=/var/vmail/%d/%n
}

# Mail location
mail_location = maildir:/var/vmail/%d/%n
mail_privileged_group = mail

ssl = required
ssl_cert = </etc/ssl/certs/server/server-cert.pem
ssl_key = </etc/ssl/certs/server/server-key.pem
ssl_min_protocol = TLSv1.2
#ssl_protocols = !SSLv3 !TLSv1 !TLSv1.1
#ssl_cipher_list = ECDHE+AESGCM:ECDHE+CHACHA20:ECDHE+AES256:ECDHE+AES128:!aNULL:!SHA1:!AESCCM
#ssl_prefer_server_ciphers = yes

# IMAP settings
service imap-login {
    # inet_listener imap {
    #    port = 143
    #    ssl = no
    # }
    inet_listener imaps {
        port = 993
        ssl = yes
    }
}

service imap {
    process_limit = 1024
}

# SASL Authentication for Postfix
service auth {
    unix_listener /var/spool/postfix/private/auth {
        mode = 0660
        user = postfix
        group = postfix
    }
}